; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -disable-output -passes="print<execution-domain>" \
; RUN:     --execution-domain-test=loop-inspect 2>&1 | FileCheck %s

@A = global [42 x i8] zeroinitializer

; for (i = 0; i < 42; i++)
;   A[i] = 0;
;
define void @single_bb() {
; CHECK-LABEL: 'single_bb'
; CHECK-NEXT:  Is safe to estimate max offset value for each pointer...
; CHECK-NEXT:    Safe
; CHECK-NEXT:        %gep = getelementptr i8, ptr @A, i64 %i
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop ]
  %gep = getelementptr i8, ptr @A, i64 %i
  store i8 0, ptr %gep
  %i.inc = add i64 %i, 1
  %ec = icmp eq i64 %i.inc, 42
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; for (i = 0; i < 42; i++)
;   if (cond)
;     A[i] = 0;
;
define void @loop_1d_cond(i1 %cond) {
; CHECK-LABEL: 'loop_1d_cond'
; CHECK-NEXT:  Is safe to estimate max offset value for each pointer...
; CHECK-NEXT:    Unsafe
; CHECK-NEXT:        %gep = getelementptr i8, ptr @A, i64 %i
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.latch ]
  %gep = getelementptr i8, ptr @A, i64 %i
  br i1 %cond, label %if.then, label %loop.latch

if.then:
  store i8 0, ptr %gep
  br label %loop.latch

loop.latch:
  %i.inc = add i64 %i, 1
  %ec = icmp eq i64 %i.inc, 42
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}

; for (i = 0; i < 4; i++)
;   for (j = 0; j < 10; j++)
;     A[i*10 + j] = 0;
;
define void @loop_2d() {
; CHECK-LABEL: 'loop_2d'
; CHECK-NEXT:  Is safe to estimate max offset value for each pointer...
; CHECK-NEXT:    Safe
; CHECK-NEXT:        %gep = getelementptr [10 x i8], ptr @A, i64 %i, i64 %j
;
entry:
  br label %loop.i.header

loop.i.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.i.latch ]
  br label %loop.j

loop.j:
  %j = phi i64 [ 0, %loop.i.header ], [ %j.inc, %loop.j ]
  %gep = getelementptr [10 x i8], ptr @A, i64 %i, i64 %j
  store i8 0, ptr %gep
  %j.inc = add i64 %j, 1
  %j.ec = icmp eq i64 %j.inc, 10
  br i1 %j.ec, label %loop.i.latch, label %loop.j

loop.i.latch:
  %i.inc = add i64 %i, 1
  %i.ec = icmp eq i64 %i.inc, 4
  br i1 %i.ec, label %exit, label %loop.i.header

exit:
  ret void
}

; for (i = 0; i < 1000; i++)
;   if (i < 2)
;     for (j = 0; j < 10; j++)
;       A[i*10 + j] = 0;
;
define void @loop_2d_br_i_j() {
; CHECK-LABEL: 'loop_2d_br_i_j'
; CHECK-NEXT:  Is safe to estimate max offset value for each pointer...
; CHECK-NEXT:    Unsafe
; CHECK-NEXT:        %gep = getelementptr [10 x i8], ptr @A, i64 %i, i64 %j
;
entry:
  br label %loop.i.header

loop.i.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.i.latch ]
  %cond = icmp slt i64 %i, 2
  br i1 %cond, label %loop.j, label %loop.i.latch

loop.j:
  %j = phi i64 [ 0, %loop.i.header ], [ %j.inc, %loop.j ]
  %gep = getelementptr [10 x i8], ptr @A, i64 %i, i64 %j
  store i8 0, ptr %gep
  %j.inc = add i64 %j, 1
  %j.ec = icmp eq i64 %j.inc, 10
  br i1 %j.ec, label %loop.i.latch, label %loop.j

loop.i.latch:
  %i.inc = add i64 %i, 1
  %i.ec = icmp eq i64 %i.inc, 1000
  br i1 %i.ec, label %exit, label %loop.i.header

exit:
  ret void
}

; for (i = 0; i < 1000; i++)
;   if (i < 2)
;     break;
;   for (j = 0; j < 10; j++)
;     A[i*10 + j] = 0;
;
define void @loop_2d_early_exit(ptr %p) {
; CHECK-LABEL: 'loop_2d_early_exit'
; CHECK-NEXT:  Is safe to estimate max offset value for each pointer...
; CHECK-NEXT:    Unsafe
; CHECK-NEXT:        %gep.1 = getelementptr [10 x i8], ptr @A, i64 %i, i64 %j
;
entry:
  br label %loop.i.header

loop.i.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.i.latch ]
  %gep.0 = getelementptr i64, ptr %p, i64 %i
  %v = load i64, ptr %gep.0
  %cond = icmp slt i64 %i, %v
  br i1 %cond, label %loop.j, label %exit

loop.j:
  %j = phi i64 [ 0, %loop.i.header ], [ %j.inc, %loop.j ]
  %gep.1 = getelementptr [10 x i8], ptr @A, i64 %i, i64 %j
  store i8 0, ptr %gep.1
  %j.inc = add i64 %j, 1
  %j.ec = icmp eq i64 %j.inc, 10
  br i1 %j.ec, label %loop.i.latch, label %loop.j

loop.i.latch:
  %i.inc = add i64 %i, 1
  %i.ec = icmp eq i64 %i.inc, 1000
  br i1 %i.ec, label %exit, label %loop.i.header

exit:
  ret void
}
