; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -disable-output -passes="print<execution-domain>" 2>&1 | FileCheck %s

; for (i = 0; i < m; i++)
;   for (j = 0; j < n; j++)
;     for (k = 0; k < o; k++)
;       A[i*n*o + j*o + k] = 0;
;
; Maybe we can infer something useful from inbounds/nusw flags.
;
define void @f(ptr %A, i64 %m, i64 %n, i64 %o) {
; CHECK-LABEL: 'f'
; CHECK-NEXT:  Context for %m:
; CHECK-NEXT:    %m sge 1
; CHECK-NEXT:    %m sle 9223372036854775807
; CHECK-NEXT:  Context for %o:
; CHECK-NEXT:    %o sge 1
; CHECK-NEXT:    %o sle 9223372036854775807
; CHECK-NEXT:  Context for %n:
; CHECK-NEXT:    %n sge 1
; CHECK-NEXT:    %n sle 9223372036854775807
; CHECK-NEXT:  Range for %m: [1,-9223372036854775808)
; CHECK-NEXT:  Range for %o: [1,-9223372036854775808)
; CHECK-NEXT:  Range for %n: [1,-9223372036854775808)
;
entry:
  %m.pos = icmp sgt i64 %m, 0
  %n.pos = icmp sgt i64 %n, 0
  %o.pos = icmp sgt i64 %o, 0
  %guard.0 = and i1 %m.pos, %n.pos
  %guard.1 = and i1 %guard.0, %o.pos
  br i1 %guard.1, label %loop.i.header, label %exit

loop.i.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.i.latch ]
  br label %loop.j.header

loop.j.header:
  %j = phi i64 [ 0, %loop.i.header ], [ %j.inc, %loop.j.latch ]
  br label %loop.k

loop.k:
  %k = phi i64 [ 0, %loop.j.header ], [ %k.inc, %loop.k ]
  %offset.0 = mul i64 %i, %n
  %offset.1 = add i64 %offset.0, %j
  %offset.2 = mul i64 %offset.1, %o
  %offset.3 = add i64 %offset.2, %k
  %gep = getelementptr inbounds i8, ptr %A, i64 %offset.3
  store i8 0, ptr %gep
  %k.inc = add i64 %k, 1
  %k.ec = icmp eq i64 %k.inc, %o
  br i1 %k.ec, label %loop.j.latch, label %loop.k

loop.j.latch:
  %j.inc = add i64 %j, 1
  %j.ec = icmp eq i64 %j.inc, %n
  br i1 %j.ec, label %loop.i.latch, label %loop.j.header

loop.i.latch:
  %i.inc = add i64 %i, 1
  %i.ec = icmp eq i64 %i.inc, %m
  br i1 %i.ec, label %exit, label %loop.i.header

exit:
  ret void
}
