; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -disable-output "-passes=print<da>" 2>&1 | FileCheck %s
; RUN: opt < %s -disable-output "-passes=print<da>" -da-enable-dependence-test=exact-siv 2>&1 \
; RUN:     | FileCheck %s --check-prefix=CHECK-EXACT-SIV

define void @exact_rdiv_large_btc(ptr %A) {
; CHECK-LABEL: 'exact_rdiv_large_btc'
; CHECK-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 0, ptr %gep.0, align 1
; CHECK-NEXT:    da analyze - none!
; CHECK-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-NEXT:    da analyze - none!
; CHECK-NEXT:  Src: store i8 1, ptr %gep.1, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-NEXT:    da analyze - none!
;
; CHECK-EXACT-SIV-LABEL: 'exact_rdiv_large_btc'
; CHECK-EXACT-SIV-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 0, ptr %gep.0, align 1
; CHECK-EXACT-SIV-NEXT:    da analyze - consistent output [*]!
; CHECK-EXACT-SIV-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-EXACT-SIV-NEXT:    da analyze - consistent output [|<]!
; CHECK-EXACT-SIV-NEXT:  Src: store i8 1, ptr %gep.1, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-EXACT-SIV-NEXT:    da analyze - consistent output [*]!
;
entry:
  br label %loop.i.header

loop.i.header:
  %i = phi i64 [ -9223372036854775808, %entry ], [ %i.inc, %loop.i.latch ]
  %cond.i = icmp sge i64 %i, 0
  br i1 %cond.i, label %if.then.0, label %loop.i.latch

if.then.0:
  %gep.0 = getelementptr i8, ptr %A, i64 %i
  store i8 0, ptr %gep.0
  br label %loop.i.latch

loop.i.latch:
  %i.inc = add i64 %i, 1
  %ec.i = icmp eq i64 %i.inc, 9223372036854775807
  br i1 %ec.i, label %loop.j.header, label %loop.i.header

loop.j.header:
  %j = phi i64 [ 9223372036854775807, %loop.i.latch ], [ %j.0.inc, %loop.j.latch ]
  %cond.j = icmp sge i64 %j, 0
  br i1 %cond.j, label %if.then.1, label %loop.j.latch

if.then.1:
  %gep.1 = getelementptr i8, ptr %A, i64 %j
  store i8 1, ptr %gep.1
  br label %loop.j.latch

loop.j.latch:
  %j.0.inc = add i64 %j, -1
  %ec.j = icmp eq i64 %j.0.inc, -9223372036854775807
  br i1 %ec.j, label %exit, label %loop.j.header

exit:
  ret void
}

