; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -disable-output "-passes=print<da>" 2>&1 | FileCheck %s
; RUN: opt < %s -disable-output "-passes=print<da>" -da-enable-dependence-test=exact-siv 2>&1 \
; RUN:     | FileCheck %s --check-prefix=CHECK-EXACT-SIV

define void @infer_affine_domain_ovfl(ptr %A) {
; CHECK-LABEL: 'infer_affine_domain_ovfl'
; CHECK-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 0, ptr %gep.0, align 1
; CHECK-NEXT:    da analyze - none!
; CHECK-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-NEXT:    da analyze - none!
; CHECK-NEXT:  Src: store i8 1, ptr %gep.1, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-NEXT:    da analyze - none!
;
; CHECK-EXACT-SIV-LABEL: 'infer_affine_domain_ovfl'
; CHECK-EXACT-SIV-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 0, ptr %gep.0, align 1
; CHECK-EXACT-SIV-NEXT:    da analyze - consistent output [*]!
; CHECK-EXACT-SIV-NEXT:  Src: store i8 0, ptr %gep.0, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-EXACT-SIV-NEXT:    da analyze - none!
; CHECK-EXACT-SIV-NEXT:  Src: store i8 1, ptr %gep.1, align 1 --> Dst: store i8 1, ptr %gep.1, align 1
; CHECK-EXACT-SIV-NEXT:    da analyze - consistent output [*]!
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.latch ]
  %offset = phi i64 [ -9223372036854775807, %entry ], [ %offset.next, %loop.latch ]
  %gep.0 = getelementptr i8, ptr %A, i64 %i
  store i8 0, ptr %gep.0
  %cond = icmp sge i64 %offset, 0
  br i1 %cond, label %if.then, label %loop.latch

if.then:
  %gep.1 = getelementptr i8, ptr %A, i64 %offset
  store i8 1, ptr %gep.1
  br label %loop.latch

loop.latch:
  %i.inc = add i64 %i, 1
  %offset.next = add nsw i64 %offset, 2305843009213693952
  %ec = icmp eq i64 %i.inc, 5
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}

