; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -disable-output "-passes=print<da>" 2>&1 | FileCheck %s
; RUN: opt < %s -disable-output "-passes=print<da>" -da-enable-dependence-test=strong-siv 2>&1 \
; RUN:     | FileCheck %s --check-prefix=CHECK-STRONG-SIV

; offset0 = -2;
; offset1 = -4;
; for (i = 0; i <= (1ULL << 63); i++) {
;   if (0 <= offset0)
;     A[offset0] = 1;
;   if (0 <= offset1)
;     A[offset1] = 2;
;   offset0 += 1;
;   offset1 += 1;
; }
define void @strong_siv_large_btc(ptr %A) {
; CHECK-LABEL: 'strong_siv_large_btc'
; CHECK-NEXT:  Src: store i8 1, ptr %gep.0, align 1 --> Dst: store i8 1, ptr %gep.0, align 1
; CHECK-NEXT:    da analyze - none!
; CHECK-NEXT:  Src: store i8 1, ptr %gep.0, align 1 --> Dst: store i8 2, ptr %gep.1, align 1
; CHECK-NEXT:    da analyze - none!
; CHECK-NEXT:  Src: store i8 2, ptr %gep.1, align 1 --> Dst: store i8 2, ptr %gep.1, align 1
; CHECK-NEXT:    da analyze - none!
;
; CHECK-STRONG-SIV-LABEL: 'strong_siv_large_btc'
; CHECK-STRONG-SIV-NEXT:  Src: store i8 1, ptr %gep.0, align 1 --> Dst: store i8 1, ptr %gep.0, align 1
; CHECK-STRONG-SIV-NEXT:    da analyze - none!
; CHECK-STRONG-SIV-NEXT:  Src: store i8 1, ptr %gep.0, align 1 --> Dst: store i8 2, ptr %gep.1, align 1
; CHECK-STRONG-SIV-NEXT:    da analyze - none!
; CHECK-STRONG-SIV-NEXT:  Src: store i8 2, ptr %gep.1, align 1 --> Dst: store i8 2, ptr %gep.1, align 1
; CHECK-STRONG-SIV-NEXT:    da analyze - none!
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.latch ]
  %offset.0 = phi i64 [ -2, %entry ], [ %offset.0.next, %loop.latch ]
  %offset.1 = phi i64 [ -4, %entry ], [ %offset.1.next, %loop.latch ]
  %cond.0 = icmp sge i64 %offset.0, 0
  br i1 %cond.0, label %if.then.0, label %loop.middle

if.then.0:
  %gep.0 = getelementptr i8, ptr %A, i64 %offset.0
  store i8 1, ptr %gep.0
  br label %loop.middle

loop.middle:
  %cond.1 = icmp sge i64 %offset.1, 0
  br i1 %cond.1, label %if.then.1, label %loop.latch

if.then.1:
  %gep.1 = getelementptr i8, ptr %A, i64 %offset.1
  store i8 2, ptr %gep.1
  br label %loop.latch

loop.latch:
  %i.inc = add i64 %i, 1
  %offset.0.next = add i64 %offset.0, 1
  %offset.1.next = add i64 %offset.1, 1
  %ec = icmp eq i64 %i, 9223372036854775808
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}
